version: '3'
services:
  db:
    container_name: url_manager-db
    image: 'postgres:15-bookworm'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  
  app:
    container_name: url_manager-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on: 
      - db  
    env_file: .env
    environment:
      RAILS_ENV: development

volumes:
  postgres_data: 