default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: postgres
    password: <%= ENV["URL_SHORTNER_DB_PASSWORD"] %>

development:
    <<: *default
    database: url_shortner

test:
    <<: *default
    database: url_shortner_test

production:
    <<: *default
    database: url_shortner
